"""Source-agnostic loader for back-adjusted commodity series.

Reads the Panama-adjusted CSVs produced by scripts/build_backadjusted.py and
presents a single aligned panel for the backtest engine. Designed so the
future Norgate backfill (M3, currently deferred) can mount additional dates
under the same interface without touching downstream code.

Currently sources:
  * Databento Panama-adjusted: 10 CME commodities (CL/NG/HO/RB/GC/SI/HG/ZC/ZS/ZW),
    2010-06-06 -> present. Generated by scripts/build_backadjusted.py.

Future (M3):
  * Norgate back-adjusted: 2000-01-01 -> 2010-06-05 (pre-Globex history)
    plus ICE trio (BRN/SB/KC) full history. Same CSV shape; stitched
    automatically when present.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

_REPO = Path(__file__).resolve().parents[2]
_DEFAULT_DATABENTO_ADJ = _REPO / "data" / "commodities" / "databento_adj"
_DEFAULT_DATABENTO_RAW = _REPO / "data" / "commodities" / "databento_raw"
_DEFAULT_NORGATE_ADJ = _REPO / "data" / "commodities" / "norgate_adj"   # future

# Stable sector taxonomy — used by signal modules and per-sector reporting.
SECTOR: dict[str, str] = {
    "CL": "Energy", "BZ": "Energy", "NG": "Energy", "HO": "Energy", "RB": "Energy",
    "GC": "Precious", "SI": "Precious",
    "HG": "Industrial",
    "ZC": "Grains", "ZS": "Grains", "ZW": "Grains",
    "SB": "Softs", "KC": "Softs",
}

LABEL: dict[str, str] = {
    "CL": "WTI crude", "BZ": "Brent crude", "NG": "Natural gas",
    "HO": "Heating oil", "RB": "RBOB gasoline",
    "GC": "Gold", "SI": "Silver", "HG": "Copper",
    "ZC": "Corn", "ZS": "Soybeans", "ZW": "Wheat",
    "SB": "Sugar #11", "KC": "Coffee C",
}

# Currently loadable instruments (those with adjusted CSVs on disk).
CME_AVAILABLE: tuple[str, ...] = (
    "CL", "NG", "HO", "RB", "GC", "SI", "HG", "ZC", "ZS", "ZW",
)


@dataclass
class CommodityPanel:
    """Aligned multi-instrument daily panel.

    Two price series per instrument:
      `close`     — Panama-adjusted close. Used by SIGNALS (SMA, Donchian,
                    momentum) because trend signals must be tradeable across
                    roll seams.
      `close_raw` — Unadjusted front-month close. Used as the RETURN
                    DENOMINATOR only.

    Why two: Panama-adjusted prices drift with cumulative roll gaps and can
    go near-zero or negative in historical segments (see milestone-2
    findings). Computing `pct_change` on the adjusted series produces wrong
    or undefined returns. The right return for a continuous-contract
    position is dollar P&L per bar (= adjusted price change) divided by the
    current contract notional (= raw front-month price):
        ret_t = adj.diff()[t] / close_raw.shift(1)[t]
    This gives well-defined percentage returns AND matches the dollar P&L a
    position-sized book actually earns.

    `close_raw` may be None for sources that don't ship a raw series; in
    that case `returns()` falls back to `adj.pct_change()` (best-effort).
    """
    close: pd.DataFrame                    # Panama-adjusted; signals + diffs
    meta: pd.DataFrame
    close_raw: pd.DataFrame | None = None  # unadjusted front; return denom

    @property
    def symbols(self) -> list[str]:
        return list(self.close.columns)

    def returns(self) -> pd.DataFrame:
        """Daily simple returns suitable for vol estimation and P&L.

        ret_t = adj.diff()[t] / raw_close.shift(1)[t]
        Falls back to adj.pct_change() if raw close not available.
        """
        if self.close_raw is None:
            return self.close.pct_change()
        # Align raw to adj index (forward-fill within reason for calendar mismatches)
        raw = self.close_raw.reindex(self.close.index).ffill(limit=2)
        diff = self.close.diff()
        denom = raw.shift(1).replace(0.0, np.nan)
        return diff / denom

    def slice(self, start: str | None = None, end: str | None = None) -> "CommodityPanel":
        c = self.close
        cr = self.close_raw
        if start:
            c = c.loc[c.index >= pd.Timestamp(start)]
            if cr is not None:
                cr = cr.loc[cr.index >= pd.Timestamp(start)]
        if end:
            c = c.loc[c.index <= pd.Timestamp(end)]
            if cr is not None:
                cr = cr.loc[cr.index <= pd.Timestamp(end)]
        return CommodityPanel(close=c, meta=self.meta, close_raw=cr)


def _load_databento_adj(symbols: Iterable[str], cache_dir: Path) -> dict[str, pd.Series]:
    out: dict[str, pd.Series] = {}
    for root in symbols:
        # File pattern: {ROOT}_v0_panama__{start}__{end}.csv
        matches = sorted(cache_dir.glob(f"{root}_v0_panama__*.csv"))
        if not matches:
            continue
        path = matches[-1]   # latest end date wins if multiple
        df = pd.read_csv(path, parse_dates=["date"]).set_index("date")
        if "close" not in df.columns:
            continue
        out[root] = df["close"].rename(root).sort_index()
    return out


def _load_databento_raw(symbols: Iterable[str], cache_dir: Path) -> dict[str, pd.Series]:
    """Load the unadjusted front-month close (the .v.0 raw cache from M1)."""
    out: dict[str, pd.Series] = {}
    for root in symbols:
        matches = sorted(cache_dir.glob(f"{root}_v_0__*.csv"))
        if not matches:
            continue
        df = pd.read_csv(matches[-1], parse_dates=["date"]).set_index("date")
        if "close" not in df.columns:
            continue
        # Sunday-collapse so the calendar matches the adj series
        from src.data.databento_loader import collapse_to_trade_date
        df = collapse_to_trade_date(df)
        out[root] = df["close"].rename(root).sort_index()
    return out


def load(
    symbols: Iterable[str] | None = None,
    databento_adj_dir: Path = _DEFAULT_DATABENTO_ADJ,
    databento_raw_dir: Path = _DEFAULT_DATABENTO_RAW,
    norgate_dir: Path = _DEFAULT_NORGATE_ADJ,
) -> CommodityPanel:
    """Load the back-adjusted panel + raw close for return computation.

    Returns the union calendar across all requested symbols. Each instrument
    is NaN before its inception in the available source; this is correct —
    the backtest engine treats NaN as "not yet trading".

    `symbols` defaults to all CME_AVAILABLE.
    """
    syms = list(symbols) if symbols else list(CME_AVAILABLE)

    series_by_sym: dict[str, pd.Series] = {}
    sources: dict[str, str] = {}

    # Databento adjusted (2010-2026)
    db = _load_databento_adj(syms, databento_adj_dir)
    for k, s in db.items():
        series_by_sym[k] = s
        sources[k] = "databento_panama"

    # Databento raw (unadjusted front-month close) — for return denominator
    raw_by_sym = _load_databento_raw(syms, databento_raw_dir)

    # Norgate adjusted (future M3): stitch under the same key if present, but
    # earlier dates. Same CSV shape expected.
    if norgate_dir.exists():
        for root in syms:
            matches = sorted(norgate_dir.glob(f"{root}_panama__*.csv"))
            if not matches:
                continue
            ng = pd.read_csv(matches[-1], parse_dates=["date"]).set_index("date")["close"].rename(root)
            if root in series_by_sym:
                # Keep databento where they overlap; use norgate only for
                # the pre-databento prefix (avoids vendor-level mismatches).
                cutoff = series_by_sym[root].index.min()
                ng = ng[ng.index < cutoff]
                series_by_sym[root] = pd.concat([ng, series_by_sym[root]]).sort_index()
                sources[root] = "norgate+databento"
            else:
                series_by_sym[root] = ng
                sources[root] = "norgate_panama"

    missing = [s for s in syms if s not in series_by_sym]
    if missing:
        raise FileNotFoundError(
            f"No back-adjusted data on disk for: {missing}. Run "
            f"`python scripts/build_backadjusted.py` (Databento) or backfill via Norgate."
        )

    close = pd.concat(series_by_sym.values(), axis=1).sort_index()
    close.index.name = "date"

    raw_present = {k: v for k, v in raw_by_sym.items() if k in close.columns}
    close_raw = (pd.concat(raw_present.values(), axis=1).sort_index()
                 if raw_present else None)
    if close_raw is not None:
        close_raw.index.name = "date"

    meta_rows = []
    for sym in close.columns:
        s = close[sym].dropna()
        meta_rows.append({
            "symbol": sym,
            "label": LABEL.get(sym, sym),
            "sector": SECTOR.get(sym, "?"),
            "source": sources.get(sym, "?"),
            "first_bar": s.index[0].date() if not s.empty else None,
            "last_bar": s.index[-1].date() if not s.empty else None,
            "n_bars": len(s),
        })
    meta = pd.DataFrame(meta_rows).set_index("symbol")
    return CommodityPanel(close=close, meta=meta, close_raw=close_raw)
